const js = require("@eslint/js")

const nodeGlobals = {
  require: "readonly",
  module: "readonly",
  exports: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  process: "readonly",
  console: "readonly",
  Buffer: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
}

const jestGlobals = {
  describe: "readonly",
  it: "readonly",
  test: "readonly",
  expect: "readonly",
  beforeEach: "readonly",
  afterEach: "readonly",
  beforeAll: "readonly",
  afterAll: "readonly",
  jest: "readonly",
}

module.exports = [
  js.configs.recommended,
  {
    files: ["**/*.js"],
    ignores: ["node_modules/**", "coverage/**"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: nodeGlobals,
    },
    rules: {
      "semi": ["error", "never"],
      "semi-spacing": ["error", { before: false, after: true }],
      "quotes": ["error", "double", { avoidEscape: true }],
      "space-before-function-paren": ["error", { anonymous: "never", named: "never", asyncArrow: "always" }],
      "space-before-blocks": "error",
      "space-infix-ops": "error",
      "space-in-parens": ["error", "never"],
      "key-spacing": ["error", { beforeColon: false, afterColon: true }],
      "comma-spacing": ["error", { before: false, after: true }],
      "arrow-spacing": ["error", { before: true, after: true }],
      "object-curly-spacing": ["error", "always"],
      "array-bracket-spacing": ["error", "never"],
      "computed-property-spacing": ["error", "never"],
      "no-multi-spaces": "error",
      "no-trailing-spaces": "error",
      "no-multiple-empty-lines": ["error", { max: 1, maxEOF: 0 }],
      "eol-last": ["error", "always"],
      "indent": ["error", 2, { SwitchCase: 1 }],
      "comma-dangle": ["error", "always-multiline"],
      "comma-style": ["error", "last"],
      "func-style": ["error", "expression"],
      "prefer-arrow-callback": "error",
      "arrow-parens": ["error", "always"],
      "arrow-body-style": ["error", "as-needed"],
      "no-param-reassign": "error",
      "no-var": "error",
      "prefer-const": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-shadow": "error",
      "no-use-before-define": ["error", { functions: false, classes: true, variables: true }],
      "eqeqeq": ["error", "always"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-return-await": "error",
      "require-await": "error",
      "no-throw-literal": "error",
      "no-promise-executor-return": "error",
      "no-console": "warn",
      "no-debugger": "error",
      "no-alert": "error",
      "no-lone-blocks": "error",
      "no-useless-return": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "prefer-template": "error",
      "object-shorthand": ["error", "always"],
      "prefer-destructuring": ["error", { array: false, object: true }],
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "no-duplicate-imports": "error",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "warn",
    },
  },
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      globals: {
        ...nodeGlobals,
        ...jestGlobals,
      },
    },
    rules: {
      "no-console": "off",
      "no-await-in-loop": "off",
      "no-shadow": "off",
    },
  },
]
